name: ditonton
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  about:
    path: about
  core:
    path: core
  animate_do: ^2.1.0
  flutter_bloc: ^8.0.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  http: ^0.13.4
  movie:
    path: movie
  intl: ^0.17.0
  path_provider: ^2.0.8
  provider: ^6.0.2
  search:
    path: search
  shimmer: ^2.0.0
  sqflite: ^2.0.1
  tv:
    path: tv


dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.17

flutter:
  uses-material-design: true

  assets:
    - assets/
